### ISSUE TITLE
Does not take in to account fractions of a percent

### ISSUE THREAD

**Issue by ghost** [jlopp/bitcoin-confirmation-risk-calculator#2]
As I point out in this post (https://bitcointalk.org/index.php?topic=5443953.msg61879707#msg61879707), fractions of a percent are not accounted for and therefore the calculated percentage risk is often inaccurate.

They are accounted correctly for in the graph produced, however.

**Comment by jlopp** [comment]
Right, this is a result of me taking the form input and running is through parseInt which drops off all decimal precision. I'll change that to parseFloat and it should resolve the discrepancy.
